name: Checks # Workflow name


on:
  pull_request:
    types: [opened, synchronize] # Workflow triggering events

jobs:
 checks:
   runs-on: ubuntu-latest

   steps:
     - name: "Checkout"
       uses: actions/checkout@v2
       with:
         fetch-depth: 0

     - name: "Use NodeJS 16"
       uses: actions/setup-node@v2 # Public action
       with:
         node-version: '16'
