name: module-versioning
on: [push, pull_request]
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install deps
        run: |
          npm i -g npm@8.8.0
          npm -v
          yarn -v
          yarn
      - name: Multi-semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USER: 'gaussb-labs'
          GIT_AUTHOR_EMAIL: 'opensource@qiwi.com'
          GIT_COMMITTER_EMAIL: 'opensource@qiwi.com'
          GIT_AUTHOR_NAME: '@qiwibot'
          GIT_COMMITTER_NAME: '@qiwibot'
        run: yarn lerna exec --concurrency 1 "npx --no-install semantic-release -e semantic-release-monorepo" && node -e "require('semantic-release-monorepo-hooks').hookAfterAll()"