name: 'Terraform CI'

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'terraform'
    runs-on: ubuntu-latest

    steps:
      - name: 'Run Script'
        run: sh tag-release [-b|--branch] [-d|--date] [-h|--help|help] [-m|--message] [-n|--dry-run] [-p|--previous] [-q|--quiet] [-r|--remote] [-t|--type] [-v|--verbose]
        shell: bash